### ISSUE TITLE
Can't use on 4.3 Phones

### ISSUE THREAD

**Issue by PutzDF** [cymcsg/UltimateRecyclerView#32]
Hi, I was using UltimateRecyclerView on my application, but it works well on my Nexys 5 (5.1) but now in my Galaxy Nexus (4.3), Am I doing something wrong?

Thanks

**Comment by cymcsg** [comment]
Do you get ``StringIndexOutOfBoundsException`` error of the sticky header?
I tried and got this error.I'll try to fix it ASAP.

**Comment by PutzDF** [comment]
I not even need to use the library, just add the library and the app can't Open

    java.lang.NoClassDefFoundError: android.support.v7.app.AppCompatDelegateImplV11
            at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:77)
            at android.support.v7.app.AppCompatActivity.getDelegate(AppCompatActivity.java:414)
            at android.support.v7.app.AppCompatActivity.onCreate(AppCompatActivity.java:57)

**Comment by cymcsg** [comment]
That is very strange. According to this [answer](http://stackoverflow.com/questions/29816687/error-showing-at-oncreate-while-using-appcompactactivity) I thought there maybe something wrong with the environment.
Do you use only `` compile 'com.marshalchen.ultimaterecyclerview:library:0.3.0'`` in your build.gradle or with some other libraries?

**Comment by PutzDF** [comment]
build.gradle... I thought it was something with my project, so I created a
new one and just added the library and got the same error.

Em sex, 8 de mai de 2015 às 06:25, MarshalChen <notifications@github.com>
escreveu:

**Comment by cymcsg** [comment]
I do not have Nexus4.3,but when I tried it on the emulator 4.3 everything got fine.
What version of UltimateRecyclerview do you use?0.3.0 or 0.3.2?

**Comment by PutzDF** [comment]
Hi, 0.3.2

Em sáb, 9 de mai de 2015 às 05:37, MarshalChen <notifications@github.com>
escreveu:

**Comment by PutzDF** [comment]
hey @cymcsg i think i know what happened, it was nothing about UltimateRecyclerView, it was about the maximum of functions permited on < 5.0, now i added the 'com.android.support:multidex:1.0.0' and everything is fine on 4.3

**Comment by cymcsg** [comment]
Thank you for reporting this.
